ALTER TABLE contas DROP CONSTRAINT IF EXISTS chk_status;

UPDATE contas SET status = 'CANCELADA'        WHERE status IN ('INATIVA', 'ENCERRADA');
UPDATE contas SET status = 'BLOQUEIO_JUDICIAL' WHERE status = 'BLOQUEADA';

ALTER TABLE contas ADD CONSTRAINT chk_status
    CHECK (status IN ('ATIVA', 'CANCELADA', 'BLOQUEIO_JUDICIAL', 'INDISPONIVEL'));